Automattic/liveblog

- liveblog.php
When using more than one loop on a single post, Liveblog inserts itself into every post on the page, not just the live blog posts.
This PR adds a check to ensure it only adds itself to the liveblog post and no others.
> We don't want Liveblog added to other loops

- README.md
- liveblog.php
- readme.txt
Bump to 1.4.1 with the addition of Composer support.
Revise tested tag to 4.2.2.
> Bump to version 1.4.1

- classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php
Creates a PHP warning, and throws out all class for each entry
> Missing end slash breaks comment classes locally

- liveblog.php
Loading on `plugins_loaded` is kinda late, especially as we want to allow folks to include the plugin in a theme (we do).
> Stop loading on a hook

- classes/class-wpcom-liveblog-entry-query.php
- classes/class-wpcom-liveblog-lazyloader.php
- css/liveblog.css
- js/liveblog-lazyloader.js
- liveblog.php
- templates/lazyload-notice.php
- templates/liveblog-key-single-list.php
- templates/liveblog-key-single-timeline.php
- templates/liveblog-loop.php
Hi there.
This pull request realizes user-driven lazyloading of Liveblog entries:
* displays a (filterable) number of entries on page load;
* fetch other entries via AJAX;
* on button click, display more entries;
* fully capable of working with (not yet displayed) Key Events;
* filters:
* `liveblog_enable_lazyloader`, enable/disable lazyloading;
* `liveblog_number_of_entries`, number of entries (for initial display, and lazyloading);
* disables _Lazyload Liveblog Entries_ plugin as it would collide with the built-in lazyloading.
> Key Events compatible lazyloading

- liveblog.php
`get_liveblog_state`, when in the admin, always assumes there is a global `$post` object set, which isn't the case quite often.
Without groking the overall internals of when this function is called, etc, returning out when it is not set fixes #220.
> Return false if there is no post global

- liveblog.php
The plugin is enqueueing its admin scripts in all admin pages. This PR adds a check to enqueue admin scripts only if adding or editing a supported post type.
> Enqueue admin scripts only if adding or editing a supported post type

- README.md
- classes/class-wpcom-liveblog-entry-key-events-widget.php
- languages/liveblog.pot
- liveblog.php
I have created a first version of the widget to display a list of key events (issue #224). It is a simple wrapper around [liveblog_key_events] shortcode and its single parameter is the widget title. The number of key events shown is controlled by the Liveblog post configuration. This is a screenshot of the widget form:
And here a screenshot of the widget displaying key entries when the user is viewing a Liveblog post:
It would be great to have general comments or suggestions on this first version since I'm still familiarizing myself with this plugin. Besides that, I have two specific questions to ask:
* The issue description (#224) suggests the use of do_shortcode() inside the widget. I decided to call WPCOM_Liveblog_Entry_Key_Events::shortcode() directly as it is more straightforward and …
> Add widget to display a list of key events

- classes/class-wpcom-liveblog-entry.php
- t/test-entry.php
- templates/liveblog-single-entry.php
As per discussion in #235 new expanded array of allowed html tags was created. It is used in template with `wp_kses` to filter post text. It is basically `wp_kses_post` + additional tags.
`iframe` was needed for embedded online content and `source` for local content.
Fixes #235
> Add tags to allow embedded video playback. 

- templates/liveblog-single-entry.php
The changes in https://github.com/Automattic/liveblog/commit/a25f2d03d9de457adb379a277265e952e3136fab broke the relative date feature in standard liveblog as the template used in the liveblog does not contain the `liveblog-time-update` class which is now used for selecting the HTML element which should bear the relative time display in https://github.com/Automattic/liveblog/blob/master/js/liveblog.js#L25
This commit adds the class to the appropriate `a` element and thus restores the functionality.
Fixes #33
> Restore the relative date feature in the liveblog.

- liveblog.php
Right now, Liveblog allows template overrides placed in theme's liveblog directory to parent themes only. Checking the child theme's directory first allows creators of the child themes to easily override parent theme's templates as well as the liveblog default ones.
Fixes #253
> Allow template overrides from child themes

- js/plupload.js
- liveblog.php
Since the Liveblog's plupload implementation is not setting a custom container option, the default one (document.body) is being used.
This may introduce some issues for certain themes since the plupload container's css position is being set to relative.
This commit is adding `liveblog_plupload_localize` filter which can be used for changing the dropzone, browser and container options inside js/plupload.js
> Adding localisation to pluploads.js

- classes/class-wpcom-liveblog-entry-query.php
Upon testing this, I noticed that liveblogs with edited entries were showing duplicates. It appears the logic in `remove_replaced_entries` was never updated when lazy loading was introduced. What's happening is that it's only searching the last X entries loaded for replaced entries, but not the entire result set. This leads to duplicates and (worse) old versions of entries becoming visible.
The only way to do this properly given the new logic is to not rely upon the `number` argument for `get_comments` and instead always fetch the full result set and handle deduping in PHP.
> Updated deduping logic for replaced entries to work properly with lazy loading

- templates/liveblog-single-entry.php
Not an ideal choice, but struggling to find another way and we need this fixed. Using
wp_kses() breaks oEmbed output and the `comment_text` filter could potentially introduce
unsafe output.
We should revisit this.
> Remove escaping so we don't break oEmbeds. Fixes #250

- classes/class-wpcom-liveblog-entry-extend.php
Chrome or Safari
contenteditable attribute in Chrome and Safari is wrapping new lines to `<div>` elements and thus links which otherwise would be standing on their own line are being wrapped in `<div>` and are not being picked up by autoembed feature of WordPress since it only takes into account links either standing on a line on their own, or wrapped in `<p>` element.
This commit is adding a new callback for `liveblog_before_insert_entry` filter which uses the same regular expression as core does for identifying link wrapped in `<p>` element (just is using div instead of p).
The preg_replace replaces the `<div>` element for `<p>` and core's autoembed feature then picks those links without issues.
> Fixes oembed links which are not working properly when publishing from

- classes/class-wpcom-liveblog-entry-instagram-oembed.php
- liveblog.php
Since the WordPress is calling the `make_clickable` function in terms of the `comment_text` filter, Instagram oEmbedes containing a plaintext link are not being properly initialised as Instagram's JS expects only a single `a` element inside the `blockquote`.
This commit is programmatically removing the script element using DomDocument and is appending a custom one, which 1) load the original script only if it has not been loaded before 2) initialise the Instagram oEmbed manually (as a side effect this fixes the issue with Instagram oEmbeds not properly working when clicking the preview button multiple times).
> Adding a new class for properly handling Instagram oembeds in previews

- classes/class-wpcom-liveblog-entry-extend.php
The original issue with oEmbeds fixed in #259 is also present during previews and updates
This commit hooks the very same function to two more filters - liveblog_before_update_entry and liveblog_before_preview_entry
> Fix the oEmbeddable links wrapped in div also on preview and update

- classes/class-wpcom-liveblog-entry-query.php
When retrieving a list of Liveblog entries, don't include any entries that have been deleted. These shouldn't be shown and can cause UI bugs.
Fixes #269
> Remove deleted entries from entry query results.

- classes/class-wpcom-liveblog-entry.php
Fixes the logic in the updating function to;
* stop passing the ID when creating a new entry,
* pass the correct ID for making a comment as a replacement,
* stop updating the original comment with new content,
* mark the original comment as trash so only the new content is shown.
Also adds some inline commenting to describe the logic.
> Prevent old versions of edited entries from appearing in the feed.

- liveblog.php
Some custom extensions for the Liveblog plugin might need to add special treatment for AJAX responses (eg.: inlining scripts as they can't use standard enququeing)
This commit adds new `liveblog_ajax_request` action which provides the $response_method param holding the name of Liveblog's method which will be used for processing the request.
This action is triggered just before the method is processed and allows developers to hook their own function calls which needs to run before the request is processed.
> Adding the `liveblog_ajax_request` action

- liveblog.php
Improve caching for ajax requests:
> Better Cache Control

- js/liveblog-publisher.js
In Chrome (OS X and Windows 8 tested) and Safari, lines after the first are wrapped in a div. e.g.
if you enter
```
a
b
c
```
you get
```
a
<div>b</div>
<div>c</div>
```
This results in unexpected HTML when published. First line gets `p` tags, but the divs stick around.
While in some cases the issue can be worked around (#259, #265), it may be better to get to the root problem.
This pull request makes Chrome and Safari insert 2 breaks (`<br /><br />`) on enter which results in predictable spacing. Instead of the divs, you'd get
```
<p>a<br>
b<br>
c</p>
```
Which is the same as Firefox currently gets.
- linebreak fix: http://stackoverflow.com/questions/18552336/prevent-contenteditable-adding-div-on-enter-chrome
- browser detection: …
> Contenteditable divs in Chrome

- css/liveblog.css
Fixes #275
Increased wrapper element size to let full icon show.
| Before | After |
| --- | --- |
| ![before](https://cloud.githubusercontent.com/assets/661330/20464244/3a88bda6-af3c-11e6-93cd-ce516a472977.png) | ![after](https://cloud.githubusercontent.com/assets/661330/20464246/4acaed7e-af3c-11e6-9fcd-21a0713bc95c.png) |
> Fix WYSIWYG icons getting cropped in MAC OS

- liveblog.php
As per #61, the plugin doesn't copy and paste the following functions from core anymore: `up_max_upload_size()`, `convert_bytes_to_hr()`, and `convert_hr_to_bytes()`
It requires them in the file if it doesn't exist.
> adding reference to function instead of copying

- classes/class-wpcom-liveblog-entry.php
As per #243, users cannot edit an entry more than once on the same page session because it will only save once (ergo, the first edit).  Problem was in rendering html, since ajax was correctly.
Credits to @trepmal for really delving into it to figure the root cause.  
This also fixes #177 and #241 going forward.
> users can edit more than 1x now and reloaded page will show

- classes/class-wpcom-liveblog-entry-query.php
- classes/class-wpcom-liveblog-wp-cli.php
As per #177, this one fixes all entries retroactively with a custom wp-cli command called `fix-archive`.  
Note: Related to #297, where #297 only fixes entries going forward.
> Retroactively fixes incorrect entries on for archived Liveblogs

- wpcom-helper.php
If the constant `A8C_PROXIED_REQUEST` is not defined, the `defined( A8C_PROXIED_REQUEST )` check will throw an error, because the value in `defined()` should be a string.
This line is causing phpunit tests in one of my projects to fail. I'll work around it for the time being by setting the constant in the test scope, but it should be fixed upstream as well.
Thanks!
> Update constant check to quote the value in defined() call

- liveblog.php
In WP 4.9 Flash and Silverlight is no longer supported, see https://core.trac.wordpress.org/ticket/41755#no0 for more details.
> Remove the deprecated options from Plupload

- README.md
- liveblog.php
- readme.txt
> Bump to v1.6.1

- src/react/Editor/Editor.js
I think that there is really no point of forcing camera capture on people - workflows differ.
It’s reasonable to assume people take pictures, edit them on the fly and then upload. Another scenario would be a reporter working form an iPad would be now able to upload an attachment received by Email.
> Don’t force mobile devices in capture mode

- t/test-rest-api.php
Allow test to return 401 or 403 as different WP versions return different results
> Fix 2 failing PHPUnit tests

- classes/class-wpcom-liveblog-entry.php
As mentioned in #346, the restricted shortcodes filter was taking in the current shortcode, therefore, it replaces all shortcodes with a blank `''`.
> Fix for issue #346 - shortcode regex issue

- classes/class-wpcom-liveblog-rest-api.php
- liveblog.php
By using get_rest_url() we can leverage the existing filters there and make sure we're consistent in the usage of REST API url.
> Use get_rest_url()

- liveblog.php
The option is returned is a `string` and the class holds the version as an `int`. The strict check causes the version check to fail and we end up flushing rewrites every time `init` fires.
Before doing the check, cast the rewrite version option as an `int` to avoid the type mismatch.
> Cast liveblog rewrite version before checks

- README.md
- readme.txt
We no longer support anything below PHP 5.6 but we haven't documented that. This change uses the core-specified mechanism in readme.
Helps address #446
> Add minimum PHP version

- CHANGELOG.md
* Fix issue with time format (#424)
* Adds check around the jetpack is_mobile flag (#428)
* Restore current user back in to localised scripts (#430)
* Cast liveblog rewrite version before checks (#439)
* Document the minimum PHP version (#447)
* Fix bug where pagination did not update (#433)
* Fix GMT offsets in entry times (#432)
props [justnorris](https://github.com/justnorris), [mjangda](https://github.com/mjangda), [paulschreiber](https://github.com/paulschreiber), [philipjohn](https://github.com/philipjohn), [scottblackburn](https://github.com/scottblackburn)
> Release 1.8.2

- classes/class-wpcom-liveblog-lazyloader.php
Originally removed in v1.7 this somehow sneaked back in, which is a problem because the JS is no longer needed and has been removed.
> Lazyload: Remove lazyloading script

- classes/class-wpcom-liveblog-amp.php
set_request_last_from_entries() is being called statically when the function isn't declared static, resulting in this error:
> Deprecated: Non-static method WPCOM_Liveblog_AMP::set_request_last_from_entries() should not be called statically in /liveblog/classes/class-wpcom-liveblog-amp.php on line 259
This change fixes that by declaring the function as static.
> Fix deprecated notice about non-static function

- src/react/services/api.js
Rather than a random scatter of timestamps, we can get a much higher cache hit-rate by forcing/normalizing multiple clients to make a request with the same timestamp.
> Round out polling timestamp

- src/react/containers/PaginationContainer.js
Fixes: https://github.com/Automattic/liveblog/issues/522
Currently when paging through liveblog entries, there are four buttons `First, Previous, Next, Last`. The buttons are properly disabled, so when on the first page, the user can not use First & Prev buttons, and on the last page the user cannot use Next & Last. However, these buttons are still visible, which can be confusing to the user.
Adding pre-existing `liveblog-btn--hide` CSS class hides these unusable buttons when they're disabled.
Moved conditionals into constants to reduce repetitiveness and improve readability.
> Fix pagination hiding of disabled buttons

- package.json
npm's getting angry at version number in package.json not being semver.
> npm ERR! Invalid version: "1.9-rc2"
See https://travis-ci.org/Automattic/liveblog/jobs/429331235#L680
> change package.json version from 1.9-rc2 to 1.9.0-rc2

- src/react/containers/EntryContainer.js
**Issue**: Oembed's don't rerender on an update.
**Fix**: Quick conditional to check if the render is changed.
> rerender oembed on update

- .travis.yml
This PR re-instates the PHPCS sniffs via Travis. It also includes the new VIP Coding Standards repo and runs the newer `WordPress-VIP-Go` standard.
Fixes #540
> Reinstate PHPCS and update VIP sniffs

- .travis.yml
HHVM is moving away from PHP compatibility, so there is little point in testing against this now.
Fixes #500.
> Travis: Remove HHVM checks

- liveblog.php
- src/react/containers/EditorContainer.js
Added a debounce to the author list box on editor to resolve issue #417 - underscores is used for the debounce, in an ideal world we would use RxJS debounce but doesn't appear possible within React Select.
Debounce is set to 500ms but theres a filter to change that `liveblog_author_list_debounce_time`
Please note I did not include complied assets so merging is cleaner.
> Add debounce to author list async box

- src/react/containers/EditorContainer.js
This is a simple way to stop editors publishing empty entries, resolves issue #475
I didn't include complied assets to make merging cleaner
> Stop editors from publishing empty entries.

- classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php
- classes/class-wpcom-liveblog-rest-api.php
This PR resolves issues #560 and #418 
We now decode content when it hits the server using `html_entity_decode()` which fixes both shortcodes and hashtags. The hashtag regex has also been updated to handle any situation where hex code does find its way into the content.
> Fix encoding issues which affect shortcodes and hashtags

- liveblog.php
Instead of sending nocache headers, which has implications for cache servers like Varnish that do `hit-for-pass`, set a short TTL so the content can be served from cache, but expires when the timestamp becomes valid.
**Example of the problem (using Varnish as an example)**:
* Varnish server that does `hit-for-pass` caching for 10 seconds
* Client makes a request for 1 second in the future
* Liveblog calls `nocache_headers()` which sets the max-age to 0 and a 1984 Expires header
* Varnish sees the object is not cacheable
* Varnish marks the object as `hit-for-pass`
* One second elapses
* Clients continue making requests for the now valid timestamp
* Those requests all go through Varnish to the origin for 10s (until `hit-for-pass` TTL expires)
* After 10s the request is recached normally …
> Cache future timestamps for a short time

- classes/class-wpcom-liveblog-amp.php
> Render AMP css safe without using esc_html to pass AMP validation

- classes/class-wpcom-liveblog-amp.php
Fixes https://github.com/Automattic/liveblog/issues/574.
> Don't run WPCOM_Liveblog_AMP::setup() on non-live posts.

- liveblog.php
> Fix PHP 7.3 Warning of continue statements targeting switch control flow structures

- classes/class-wpcom-liveblog-wp-cli.php
As of WordPress 4.6, the `comment` cache group is persistent. Thus, after any direct SQL query which `INSERT`s, `UPDATE`s, or `DELETE`s data in comments table, the `clean_comment_cache` function should be called, in order to make the changes immediatelly visible in case a persistent object cache backend (memcache, redis...) is used.
This commit also calls the `update_meta_cache` function after direct SQL edits to `commentmeta` table.
see https://make.wordpress.org/core/2016/07/18/comments-in-4-6-can-now-be-cached-by-a-persistent-object-cache/
Fixes #657
> Clean comment cache after direct SQL queries.

- classes/class-wpcom-liveblog-rest-api.php
WordPress 5.5+ throws a doing_it_wrong notice when a route is registered without a permission_callback.
https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/
Since these endpoints are intended to be public, the `__return_true` callback can be used.
> REST API routes require a permission_callback

- liveblog.php
In essence, and as discussed way back in 2014 but [thought to be a core bug](https://github.com/Automattic/liveblog/pull/123#issuecomment-32673846), the error in #219 happens whenever another plugin uses `WP_Query` before the main query is created. As @kevinlisota quite [correctly pointed out](https://github.com/Automattic/liveblog/issues/219#issuecomment-198998787) this causes Liveblog's `add_custom_post_type_support()` to be invoked, leading to the `get_query_var()` call that ultimately results in a Fatal Error.
It seemed a little strange to me that `pre_get_posts` was the hook used for adding CPT support so I chose to move it to `after_setup_theme` and in my testing, Liveblog behaved exactly as expected.
Fixes #219
> Load CPT support later to avoid fatals with early use of WP_Query

- CHANGELOG.md
- README.md
- classes/class-wpcom-liveblog-rest-api.php
- liveblog.php
- readme.txt
**Description**
This PR has been made to a capability check to the preview ajax/rest endpoints, and the get author/hashtag rest endpoints so as to prevent unauthenticated calls from being made. This leverages the existing method already being used for various other endpoints.
> Fix the unathenticated vulnerability for ajax/rest endpoints

- classes/class-wpcom-liveblog-wp-cli.php
The docs for `WP_CLI::line()` recommend using `WP_CLI::log()`:
> WP_CLI::log() is typically recommended and WP_CLI::line() is included only for historical compat.
https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-line/
This PR updates references to `WP_CLI::line()` to use `WP_CLI::log()` instead.
> Update WP_CLI::line() to WP_CLI::log()
