Automattic/liveblog

- classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php
catches hypens now, rather than just first word
> Changing preg to not break on mulitple words separated by hypens

- classes/class-wpcom-liveblog-entry-key-events.php
- liveblog.php
- templates/liveblog-key-admin.php
> Adding limit field for key events, configurable per post

- classes/class-wpcom-liveblog-entry-key-events.php
- classes/class-wpcom-liveblog-entry.php
- js/liveblog-publisher.js
- liveblog.php
- templates/liveblog-key-events.php
- templates/liveblog-key-single-list.php
- templates/liveblog-key-single-timeline.php
> Removing key events

- README.md
- liveblog.php
- readme.txt
Updates the readme files and plugin header
> Release prep for 1.5

- README.md
Or at least I think they are typos (I'm never sure when I think I found a typo since English is not my mother language ;))
> Fix minor typo in the README.md file

- wpcom-helper.php
Some of these changes are expected by WP.com systems and how we support the liveblog plugin.
> Update WPCom helper to include all modifications applied to v1.3

- wpcom-helper.php
Fixes issues in Quickstart where BlackbirdPie is not available.
> Fail gracefully if BlackbirdPie isn't available.

- wpcom-helper.php
> Add function_exists checks for WP.com functions

- liveblog.php
Some of which has been implemented :)
> Remove old "things yet to be implemented" list

- classes/class-wpcom-liveblog-entry-extend-feature-authors.php
- classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php
- classes/class-wpcom-liveblog-rest-api.php
- js/liveblog-admin.js
- js/liveblog-lazyloader.js
- js/liveblog-publisher.js
- js/liveblog.js
- liveblog.php
- t/bootstrap.php
- t/class-wp-test-spy-rest-server.php
- t/test-rest-api.php
Re-opening PR by @travisw (see #240) which was (auto)closed due to removal of the `develop` branch. This one is against `master` instead.
/cc @philipjohn
> REST API Endpoints

- liveblog.php
- templates/settings-page.php
Liveblog-enabled posts older than the given limit (default: 7) days will become archived posts.
Can be disabled by the admin.
Fixes #87.
> Adding an auto-archive feature.

- classes/class-wpcom-liveblog-rest-api.php
- t/test-rest-api.php
Fixes self-hosted multisite issue #320
> Fix #320: Always return a full URL when building endpoint base

- classes/class-wpcom-liveblog-rest-api.php
Reverts Automattic/liveblog#354
> Revert "Use get_rest_url()"

- CHANGELOG.md
- README.md
- liveblog.php
- readme.txt
Update version numbers and changelog for v1.8.1
> Release 1.8.1

- liveblog.php
Adds conditional around jetpack `is_mobile` flag as having jetpack installed was assumed.
> Adds check around the jetpack is_mobile flag

- classes/class-wpcom-liveblog-lazyloader.php
The lazyload JS has been deprecated, so remove it.
> Remove deprecated lazyload jS

- liveblog.php
> remove commented-out debug code

- README.md
- liveblog.php
- readme.txt
Changes the plugin description in the plugin header and readme files.
> Update the description to use the new "Vision" statement.

- classes/class-wpcom-liveblog-amp-template.php
- classes/class-wpcom-liveblog-amp.php
- liveblog.php
- templates/amp/entry.php
- templates/amp/feed.php
Fixes a number of PHPCS issues present in v1.9.1.
The only ones not dealt with here are covered in #543
> PHPCS fixes for v1.9.1

- classes/class-wpcom-liveblog-entry.php
Remove get_fields_for_render(), which appears to be unused. Fixes #596.
> remove get_fields_for_render()

- classes/class-wpcom-liveblog-entry.php
Reverts Automattic/liveblog#597
> Revert "remove get_fields_for_render()"

- classes/class-wpcom-liveblog-entry-embed-sdks.php
Currently in liveblog plugin we are using  wrong reddit media js file ie. https://embed.redditmedia.com/widgets/platform.js?ver=1.9.7
https://embed.redditmedia.com/widgets/platform.js is redirecting on https://embed.reddit.com/widgets.js, which is impacting performance as well as Page speed.
After pushing found if we are adding version then  js file does not work , version based sdk going 404 not found, we don't needs to add version variable in sdk js file
Instagram js also changed https://platform.instagram.com/en_US/embeds.js redirecting on https://www.instagram.com/embed.js
> Liveblog embed.redditmedia.com javascript file returning 404
